In [1]:

import pandas as pd
df=pd.read_csv("ufc_gold_dataset_final.csv")
df.head()

,Fight_URL,Fighter_1,Fighter_2,Winner,Weight_Class,Method,End_Round,End_Time,Total_Fight_Time_Sec,Time_Format,...,F2_Body,F1_Leg,F2_Leg,F1_Distance,F2_Distance,F1_Clinch,F2_Clinch,F1_Ground,F2_Ground,Event_Date
0,http://ufcstats.com/fight-details/4acab67848e7...,Scott Morris,Sean Daugherty,Scott Morris,Open Weight Bout,Submission,1,0:20,20,No Time Limit,...,0,0,0,0,0,1,0,0,0,1994-03-11
1,http://ufcstats.com/fight-details/4b9ae533ccb3...,Patrick Smith,Ray Wizard,Patrick Smith,Open Weight Bout,Submission,1,0:58,58,No Time Limit,...,0,0,1,0,1,1,0,0,0,1994-03-11
2,http://ufcstats.com/fight-details/00835554f95f...,Royce Gracie,Patrick Smith,Royce Gracie,UFC 2 Tournament Title Bout,KO/TKO,1,1:17,77,No Time Limit,...,1,1,0,0,0,1,1,3,0,1994-03-11
3,http://ufcstats.com/fight-details/aa161c715974...,Royce Gracie,Remco Pardoel,Royce Gracie,Open Weight Bout,Submission,1,1:31,91,No Time Limit,...,0,0,0,0,0,0,0,0,0,1994-03-11
4,http://ufcstats.com/fight-details/8fbdde20b712...,Patrick Smith,Johnny Rhodes,Patrick Smith,Open Weight Bout,Submission,1,1:07,67,No Time Limit,...,0,2,2,3,4,2,0,0,0,1994-03-11

In [2]:
import kagglehub
import pandas as pd
import matplotlib.pyplot as plt
import glob
import os

# Download UFC dataset
path = kagglehub.dataset_download(
    "jossilva3110/ufc-dataset-1994-2026"
)

# Find CSV file automatically
csv_files = glob.glob(
    os.path.join(path, "**", "*.csv"),
    recursive=True
)

print("CSV files found:")
for file in csv_files:
    print(file)

# Load the first CSV file
df = pd.read_csv(csv_files[0])

print("\nDataset loaded successfully!")
print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

# Display first 5 records
display(df.head())

CSV files found:
C:\Users\DELL\.cache\kagglehub\datasets\jossilva3110\ufc-dataset-1994-2026\versions\1\ufc_fighters_final.csv
C:\Users\DELL\.cache\kagglehub\datasets\jossilva3110\ufc-dataset-1994-2026\versions\1\ufc_gold_dataset_final.csv

Dataset loaded successfully!
Shape: (4455, 18)

Columns:
['Fighter_Name', 'Height', 'Weight', 'Reach', 'Stance', 'DOB', 'Wins', 'Losses', 'Draws', 'SLpM', 'Str_Acc', 'SApM', 'Str_Def', 'TD_Avg', 'TD_Acc', 'TD_Def', 'Sub_Avg', 'Fighter_URL']

,Fighter_Name,Height,Weight,Reach,Stance,DOB,Wins,Losses,Draws,SLpM,Str_Acc,SApM,Str_Def,TD_Avg,TD_Acc,TD_Def,Sub_Avg,Fighter_URL
0,Tom Aaron,NaN,155 lbs.,NaN,NaN,1978-07-13,5,3,0,0.00,0%,0.00,0%,0.00,0%,0%,0.0,http://ufcstats.com/fighter-details/93fe7332d1...
1,Danny Abbadi,"5' 11""",155 lbs.,NaN,Orthodox,1983-07-03,4,6,0,3.29,38%,4.41,57%,0.00,0%,77%,0.0,http://ufcstats.com/fighter-details/15df64c02b...
2,Nariman Abbasov,"5' 8""",155 lbs.,"66.0""",Orthodox,1994-02-01,28,4,0,3.00,20%,5.67,46%,0.00,0%,66%,0.0,http://ufcstats.com/fighter-details/59a9d6dac6...
3,Darion Abbey,"6' 2""",265 lbs.,"80.0""",Orthodox,1993-02-25,9,5,0,8.44,50%,14.06,28%,0.00,0%,0%,0.0,http://ufcstats.com/fighter-details/4961467134...
4,David Abbott,"6' 0""",265 lbs.,NaN,Switch,1965-04-26,10,15,0,1.35,30%,3.55,38%,1.07,33%,66%,0.0,http://ufcstats.com/fighter-details/b361180739...